MODULE = cc26xx_cc13xx_coresdk_drivers

DIRS += rf

SDK_DRIVERS = $(CURDIR)/../vendor/coresdk_cc13xx_cc26xx/source/ti/drivers
PREBUILT_LIB = $(SDK_DRIVERS)/lib/drivers_$(CPU).am4fg

include $(RIOTMAKE)/prebuilt.inc.mk
