MODULE = cc26xx_cc13xx_coresdk_drivers_rf

SDK_DRIVERS = $(CURDIR)/../../vendor/coresdk_cc13xx_cc26xx/source/ti/drivers
PREBUILT_LIB = $(SDK_DRIVERS)/rf/lib/rf_multiMode_$(CPU).am4fg

include $(RIOTMAKE)/prebuilt.inc.mk
