MODULE = cc26xx_cc13xx_coresdk_nortos

# e.g.: cc13x2
SDK_LIB_NAME = $(CPU)

SDK_NORTOS = $(CURDIR)/../vendor/coresdk_cc13xx_cc26xx/kernel/nortos

PREBUILT_LIB = $(SDK_NORTOS)/lib/nortos_$(CPU).am4fg

include $(RIOTMAKE)/prebuilt.inc.mk
