# Define the module that is built:
MODULE = cpu

# Add a list of subdirectories, that should also be built:
DIRS += periph interrupt
DIRS += $(RIOTCPU)/cortexm_common $(RIOTCPU)/cc26xx_cc13xx

include $(RIOTBASE)/Makefile.base
